# Generated by Django 3.0.5 on 2020-04-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='next_bill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
