# Generated by Django 3.0.5 on 2020-04-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0002_auto_20200410_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='checkout_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
